services:
  n8n:
    build: .
    platform: linux/amd64
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: '${DB_POSTGRESDB_HOST}'
      DB_POSTGRESDB_PORT: '${DB_POSTGRESDB_PORT}'
      DB_POSTGRESDB_DATABASE: '${DB_POSTGRESDB_DATABASE}'
      DB_POSTGRESDB_USER: '${DB_POSTGRESDB_USER}'
      DB_POSTGRESDB_PASSWORD: '${DB_POSTGRESDB_PASSWORD}'
      QUEUE_BULL_REDIS_HOST: '${QUEUE_BULL_REDIS_HOST}'
      QUEUE_BULL_REDIS_PORT: '${QUEUE_BULL_REDIS_PORT}'
      QUEUE_BULL_REDIS_PASSWORD: '${QUEUE_BULL_REDIS_PASSWORD}'
      N8N_HOST: '${N8N_HOST}'
      WEBHOOK_URL: '${WEBHOOK_URL}'
      N8N_LOG_LEVEL: '${N8N_LOG_LEVEL}'
      GENERIC_TIMEZONE: '${GENERIC_TIMEZONE}'
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: '${N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE}'
    volumes:
      - n8n_data:/home/node/.n8n
      - ./temp:/home/node/temp
      - ./waha_media/default:/home/node/waha_media/default
    ports:
      - '5678:5678'

  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: '${WAHA_WEBHOOK_URL}'
      WHATSAPP_DEFAULT_ENGINE: '${WAHA_DEFAULT_ENGINE}'
      WHATSAPP_HOOK_EVENTS: '${WAHA_HOOK_EVENTS}'
    volumes:
      - waha_sessions:/app/.sessions
      - ./waha_media:/tmp/whatsapp-files 
    ports:
      - "3000:3000"

 doc2md:
    image: felipefontoura/doc2md:latest
    networks:
      - network_public
    environment:
      - OPENAI_API_KEY=${DOC2MD_OPENAI_API_KEY}
      - LLM_MODEL=${DOC2MD_LLM_MODEL}
      - WORKERS=${DOC2MD_WORKERS}
      - TIMEOUT=${DOC2MD_TIMEOUT}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.doc2md.rule=Host(`${DOC2MD_DOMAIN}`)
        - traefik.http.routers.doc2md.entrypoints=websecure
        - traefik.http.routers.doc2md.tls.certresolver=letsencryptresolver
        - traefik.http.routers.doc2md.priority=1
        - traefik.http.routers.doc2md.service=doc2md
        - traefik.http.services.doc2md.loadbalancer.server.port=5000
        - traefik.http.services.doc2md.loadbalancer.passHostHeader=true

volumes:
  n8n_data:
  waha_sessions:
  waha_media:

networks:
  network_public:
    external: true
