version: "3.9"

services:
  n8n:
    build: .
    platform: linux/amd64
    restart: unless-stopped
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: "${DB_POSTGRESDB_HOST}"
      DB_POSTGRESDB_PORT: "${DB_POSTGRESDB_PORT}"
      DB_POSTGRESDB_DATABASE: "${DB_POSTGRESDB_DATABASE}"
      DB_POSTGRESDB_USER: "${DB_POSTGRESDB_USER}"
      DB_POSTGRESDB_PASSWORD: "${DB_POSTGRESDB_PASSWORD}"
      QUEUE_BULL_REDIS_HOST: "${QUEUE_BULL_REDIS_HOST}"
      QUEUE_BULL_REDIS_PORT: "${QUEUE_BULL_REDIS_PORT}"
      QUEUE_BULL_REDIS_PASSWORD: "${QUEUE_BULL_REDIS_PASSWORD}"

      N8N_HOST: "${N8N_HOST}"
      N8N_PROTOCOL: "${N8N_PROTOCOL}"
      WEBHOOK_URL: "${WEBHOOK_URL}"
      N8N_LOG_LEVEL: "${N8N_LOG_LEVEL}"
      GENERIC_TIMEZONE: "${GENERIC_TIMEZONE}"
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: "${N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE}"
      N8N_RUNNERS_ENABLED: "${N8N_RUNNERS_ENABLED}"
      N8N_TRUST_PROXY: "${N8N_TRUST_PROXY}"

      N8N_BASIC_AUTH_ACTIVE: "${N8N_BASIC_AUTH_ACTIVE}"
      N8N_BASIC_AUTH_USER: "${N8N_BASIC_AUTH_USER}"
      N8N_BASIC_AUTH_PASSWORD: "${N8N_BASIC_AUTH_PASSWORD}"
      N8N_PUBLIC_API_DISABLED: "${N8N_PUBLIC_API_DISABLED}"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "${N8N_BLOCK_ENV_ACCESS_IN_NODE}"
      N8N_SECURE_COOKIE: "${N8N_SECURE_COOKIE}"
      N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY}"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}"
      NODE_ENV: "${NODE_ENV}"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./temp:/home/node/temp
      - ./waha_media/default:/home/node/waha_media/default

  waha:
    image: "${WAHA_IMAGE}"
    platform: linux/amd64
    restart: unless-stopped
    environment:
      # Bind correto (não usar HOST/PORT genéricos)
      WHATSAPP_API_HOSTNAME: "${WHATSAPP_API_HOSTNAME}"
      WHATSAPP_API_PORT: "${WHATSAPP_API_PORT}"

      # App
      WHATSAPP_DEFAULT_ENGINE: "${WAHA_DEFAULT_ENGINE}"
      WHATSAPP_HOOK_URL: "${WAHA_WEBHOOK_URL}"
      WHATSAPP_HOOK_EVENTS: "${WAHA_HOOK_EVENTS}"

      WAHA_DASHBOARD_ENABLED: "${WAHA_DASHBOARD_ENABLED}"
      WHATSAPP_SWAGGER_ENABLED: "${WHATSAPP_SWAGGER_ENABLED}"

      # Segurança
      WAHA_API_KEY: "sha512:${WAHA_API_KEY_SHA512}"
      WAHA_API_KEY_EXCLUDE_PATH: "${WAHA_API_KEY_EXCLUDE_PATH}"
      WAHA_PRINT_QR: "${WAHA_PRINT_QR}"

    volumes:
      - waha_sessions:/app/.sessions
      - ./waha_media:/tmp/whatsapp-files

    healthcheck:
      # /health agora responde 200 sem X-Api-Key
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${WHATSAPP_API_PORT}/health >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  n8n_data:
  waha_sessions:
  waha_media:
