services:
  n8n:
    build: .
    platform: linux/amd64
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: '${DB_POSTGRESDB_HOST}'
      DB_POSTGRESDB_PORT: '${DB_POSTGRESDB_PORT}'
      DB_POSTGRESDB_DATABASE: '${DB_POSTGRESDB_DATABASE}'
      DB_POSTGRESDB_USER: '${DB_POSTGRESDB_USER}'
      DB_POSTGRESDB_PASSWORD: '${DB_POSTGRESDB_PASSWORD}'
      QUEUE_BULL_REDIS_HOST: '${QUEUE_BULL_REDIS_HOST}'
      QUEUE_BULL_REDIS_PORT: '${QUEUE_BULL_REDIS_PORT}'
      QUEUE_BULL_REDIS_PASSWORD: '${QUEUE_BULL_REDIS_PASSWORD}'
      N8N_HOST: '${N8N_HOST}'
      WEBHOOK_URL: '${WEBHOOK_URL}'
      N8N_LOG_LEVEL: '${N8N_LOG_LEVEL}'
      GENERIC_TIMEZONE: '${GENERIC_TIMEZONE}'
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: '${N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE}'
    volumes:
      - n8n_data:/home/node/.n8n
      - ./temp:/home/node/temp
      - ./waha_media/default:/home/node/waha_media/default
    ports:
      - '5678:5678'

  waha:
    image: devlikeapro/waha-plus:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: '${WAHA_WEBHOOK_URL}'
      WHATSAPP_DEFAULT_ENGINE: '${WAHA_DEFAULT_ENGINE}'
      WHATSAPP_HOOK_EVENTS: '${WAHA_HOOK_EVENTS}'
    volumes:
      - waha_sessions:/app/.sessions
      - ./waha_media:/tmp/whatsapp-files 
    ports:
      - "3000:3000"
      
volumes:
  n8n_data:
  waha_sessions:
  waha_media:
